### ISSUE TITLE
Support needed for mix protocol  for service type=loadBalancer

### ISSUE THREAD

**Issue by kaurkp** [sofianinho/iperf3-docker#2]
To support multiple protocols (TCP,UDP and SCTP) within a single service (type: loadbalancer). 

Some loadbalancer implementation allows to support distinct port service within a single service like -**Metallb**. We need to set:

- Make use of different ports numbers is needed for different protocols (e.g. tcp/80 for one and udp/443 for the other). whereas, in the case of iperf3-docker assign to port 5201 for each protocol. Can we do something inorder to solve this issue.

**Comment by sofianinho** [comment]
@kaurkp thank you for your Pull request, I just accepted it :-)  Can you update the README file to show how to use it ?

**Comment by kaurkp** [comment]
@sofianinho Great and thank you for accepting :-) for the part to update README we already have README for the metallb part but for the use of these descriptor files I will do it soon surely.

BR,

**Comment by kaurkp** [comment]
@sofianinho  as we found the solution for this raised issues, with some possibility on metallb, Also in order to do so we need to create two seperate services one for TCP and other for UDP (or any desired protocols) with required annotation of metallb. I'll make required changes in descriptors as well.
